project:
  type: website

website:
  title: "Santsibyllah Seitz"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Projects
        


format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

